#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect
# nginx installation requirements

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
