#!/usr/bin/env bash
# Installs and configures HAproxy on your load balancer server

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
        server 247325-web-01 100.26.225.229:80 check
        server 247325-web-02 100.25.144.170:80 check

frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
