#!/usr/bin/env bash
# Installs and configures HAproxy on your load balancer server

apt-get install -y  --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get install -y haproxy

echo "
backend web_backend
        balance roundrobin
        server 247325-web-01 100.26.225.229:80 check
        server 247325-web-02 100.25.144.170:80 check

frontend web_backend
        bind *:80
        mode http
        default_backend web_backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
