#!/usr/bin/env bash
# This Script displays Best School 10 times but "hi" on the 9th iteration

i=0
while [[ $i -lt 10 ]]; do
	echo "Best School"
	if (( i == 8 )); then
		echo "Hi"
	fi
	i=$((i + 1))
done
