#!/usr/bin/env bash
# Bash script that displays the content of the current directory in list format

list="$(ls -1)"

for file in $list; do
	filename=$(echo "$file" | cut -d'-' -f2-)
	echo "$filename"
done
